<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Metaphor.Processing</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <OptionStrict>On</OptionStrict>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Model\Characters\Character\Pace\**" />
    <EmbeddedResource Remove="Model\Characters\Character\Pace\**" />
    <None Remove="Model\Characters\Character\Pace\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Metaphor.Initializers\Metaphor.Initializers.vbproj" />
    <ProjectReference Include="..\TGGD.Processing\TGGD.Processing.vbproj" />
  </ItemGroup>

</Project>
