Public Module VerbSubtypes
    Public Const ADD_BAKING_POWDER As String = NameOf(ADD_BAKING_POWDER)
    Public Const ADD_BUTTER As String = NameOf(ADD_BUTTER)
    Public Const ADD_EGG As String = NameOf(ADD_EGG)
    Public Const ADD_FLOUR As String = NameOf(ADD_FLOUR)
    Public Const ADD_MILK As String = NameOf(ADD_MILK)
    Public Const ADD_SALT As String = NameOf(ADD_SALT)
    Public Const ADD_SUGAR As String = NameOf(ADD_SUGAR)
    Public Const ADD_VANILLA As String = NameOf(ADD_VANILLA)
    Public Const BUY_SUPPLIES As String = NameOf(BUY_SUPPLIES)
    Public Const BAKE_CAKE As String = NameOf(BAKE_CAKE)
    Public Const CLOSE_DOOR As String = NameOf(CLOSE_DOOR)
    Public Const EMPTY_MIXING_BOWL As String = NameOf(EMPTY_MIXING_BOWL)
    Public Const ENTER As String = NameOf(ENTER)
    Public Const MIX As String = NameOf(MIX)
    Public Const OPEN_DOOR As String = NameOf(OPEN_DOOR)
    Public Const POUR_BATTER As String = NameOf(POUR_BATTER)
    Public Const PUT_CAKE_PAN_IN As String = NameOf(PUT_CAKE_PAN_IN)
    Public Const SELL_CAKE As String = NameOf(SELL_CAKE)
    Public Const SLEEP As String = NameOf(SLEEP)
    Public Const TAKE_CAKE_PAN_OUT As String = NameOf(TAKE_CAKE_PAN_OUT)
    Public Const TURN_OFF As String = NameOf(TURN_OFF)
    Public Const TURN_ON As String = NameOf(TURN_ON)
    Public Const UNMOLD_CAKE As String = NameOf(UNMOLD_CAKE)
End Module
