Friend Module VerbSubtypes
    Friend Const ADD_BAKING_POWDER As String = NameOf(ADD_BAKING_POWDER)
    Friend Const ADD_BUTTER As String = NameOf(ADD_BUTTER)
    Friend Const ADD_EGG As String = NameOf(ADD_EGG)
    Friend Const ADD_FLOUR As String = NameOf(ADD_FLOUR)
    Friend Const ADD_MILK As String = NameOf(ADD_MILK)
    Friend Const ADD_SALT As String = NameOf(ADD_SALT)
    Friend Const ADD_SUGAR As String = NameOf(ADD_SUGAR)
    Friend Const ADD_VANILLA As String = NameOf(ADD_VANILLA)
    Friend Const BAKE_CAKE As String = NameOf(BAKE_CAKE)
    Friend Const CLOSE_DOOR As String = NameOf(CLOSE_DOOR)
    Friend Const EMPTY_MIXING_BOWL As String = NameOf(EMPTY_MIXING_BOWL)
    Friend Const ENTER As String = NameOf(ENTER)
    Friend Const MIX As String = NameOf(MIX)
    Friend Const OPEN_DOOR As String = NameOf(OPEN_DOOR)
    Friend Const POUR_BATTER As String = NameOf(POUR_BATTER)
    Friend Const PUT_CAKE_PAN_IN As String = NameOf(PUT_CAKE_PAN_IN)
    Friend Const SLEEP As String = NameOf(SLEEP)
    Friend Const TAKE_CAKE_PAN_OUT As String = NameOf(TAKE_CAKE_PAN_OUT)
    Friend Const TURN_OFF As String = NameOf(TURN_OFF)
    Friend Const TURN_ON As String = NameOf(TURN_ON)
End Module
