Friend Module VerbSubtypes
    Friend Const ACCEPT_DELIVERY As String = NameOf(ACCEPT_DELIVERY)
    Friend Const BUY_FUEL As String = NameOf(BUY_FUEL)
    Friend Const CHARGE_BATTERY As String = NameOf(CHARGE_BATTERY)
    Friend Const DELIVER_PACKAGE As String = NameOf(DELIVER_PACKAGE)
    Friend Const DISEMBARK As String = NameOf(DISEMBARK)
    Friend Const DOCK As String = NameOf(DOCK)
    Friend Const EAT As String = NameOf(EAT)
    Friend Const EMBARK As String = NameOf(EMBARK)
    Friend Const HEAD_FOR_KNOWN_BUBBLE As String = NameOf(HEAD_FOR_KNOWN_BUBBLE)
    Friend Const LOWER_SNORKEL As String = NameOf(LOWER_SNORKEL)
    Friend Const MOVE As String = NameOf(MOVE)
    Friend Const RAISE_SNORKEL As String = NameOf(RAISE_SNORKEL)
    Friend Const SET_HEADING As String = NameOf(SET_HEADING)
    Friend Const SET_HYDROPLANE As String = NameOf(SET_HYDROPLANE)
    Friend Const SET_SPEED As String = NameOf(SET_SPEED)
    Friend Const STOW As String = NameOf(STOW)
    Friend Const TAKE As String = NameOf(TAKE)
    Friend Const UNDOCK As String = NameOf(UNDOCK)
    Friend Const WAIT As String = NameOf(WAIT)
End Module
