Friend Module Dimensions
    Friend Const BATTERY As String = NameOf(BATTERY)
    Friend Const DEPTH As String = NameOf(DEPTH)
    Friend Const ENGINE As String = NameOf(ENGINE)
    Friend Const FUEL As String = NameOf(FUEL)
    Friend Const HEADING As String = NameOf(HEADING)
    Friend Const HYDROPLANE As String = NameOf(HYDROPLANE)
    Friend Const JOOLS As String = NameOf(JOOLS)
    Friend Const LATITUDE As String = NameOf(LATITUDE)
    Friend Const LONGITUDE As String = NameOf(LONGITUDE)
    Friend Const OXYGEN As String = NameOf(OXYGEN)
    Friend Const SPEED As String = NameOf(SPEED)
    Friend Const VISIBILITY As String = NameOf(VISIBILITY)
    Friend Const FUEL_PRICE As String = NameOf(FUEL_PRICE)
End Module
